var annotated_dup =
[
    [ "carta", "namespacecarta.html", [
      [ "FileInfo", "namespacecarta_1_1FileInfo.html", [
        [ "ImageStats", "structcarta_1_1FileInfo_1_1ImageStats.html", "structcarta_1_1FileInfo_1_1ImageStats" ],
        [ "RegionStatsId", "structcarta_1_1FileInfo_1_1RegionStatsId.html", "structcarta_1_1FileInfo_1_1RegionStatsId" ],
        [ "RegionSpectralStats", "structcarta_1_1FileInfo_1_1RegionSpectralStats.html", "structcarta_1_1FileInfo_1_1RegionSpectralStats" ]
      ] ],
      [ "ConfigId", "structcarta_1_1ConfigId.html", "structcarta_1_1ConfigId" ],
      [ "ConfigIdHash", "structcarta_1_1ConfigIdHash.html", "structcarta_1_1ConfigIdHash" ],
      [ "CacheId", "structcarta_1_1CacheId.html", "structcarta_1_1CacheId" ],
      [ "CacheIdHash", "structcarta_1_1CacheIdHash.html", "structcarta_1_1CacheIdHash" ],
      [ "HistogramConfig", "structcarta_1_1HistogramConfig.html", "structcarta_1_1HistogramConfig" ],
      [ "RegionHistogramConfig", "structcarta_1_1RegionHistogramConfig.html", "structcarta_1_1RegionHistogramConfig" ],
      [ "HistogramCache", "structcarta_1_1HistogramCache.html", "structcarta_1_1HistogramCache" ],
      [ "SpectralConfig", "structcarta_1_1SpectralConfig.html", "structcarta_1_1SpectralConfig" ],
      [ "RegionSpectralConfig", "structcarta_1_1RegionSpectralConfig.html", "structcarta_1_1RegionSpectralConfig" ],
      [ "SpectralCache", "structcarta_1_1SpectralCache.html", "structcarta_1_1SpectralCache" ],
      [ "RegionStatsConfig", "structcarta_1_1RegionStatsConfig.html", "structcarta_1_1RegionStatsConfig" ],
      [ "StatsCache", "structcarta_1_1StatsCache.html", "structcarta_1_1StatsCache" ],
      [ "TileCache", "classcarta_1_1TileCache.html", "classcarta_1_1TileCache" ],
      [ "TileCacheKey", "structcarta_1_1TileCacheKey.html", "structcarta_1_1TileCacheKey" ],
      [ "TilePool", "structcarta_1_1TilePool.html", "structcarta_1_1TilePool" ],
      [ "Tile", "structcarta_1_1Tile.html", "structcarta_1_1Tile" ],
      [ "VectorField", "classcarta_1_1VectorField.html", "classcarta_1_1VectorField" ],
      [ "FileExtInfoLoader", "classcarta_1_1FileExtInfoLoader.html", "classcarta_1_1FileExtInfoLoader" ],
      [ "FileInfoLoader", "classcarta_1_1FileInfoLoader.html", "classcarta_1_1FileInfoLoader" ],
      [ "FileListHandler", "classcarta_1_1FileListHandler.html", "classcarta_1_1FileListHandler" ],
      [ "FitsHduList", "classcarta_1_1FitsHduList.html", "classcarta_1_1FitsHduList" ],
      [ "ContourSettings", "structcarta_1_1ContourSettings.html", "structcarta_1_1ContourSettings" ],
      [ "Frame", "classcarta_1_1Frame.html", "classcarta_1_1Frame" ],
      [ "HttpServer", "classcarta_1_1HttpServer.html", "classcarta_1_1HttpServer" ],
      [ "CartaFitsImage", "classcarta_1_1CartaFitsImage.html", "classcarta_1_1CartaFitsImage" ],
      [ "CartaHdf5Image", "classcarta_1_1CartaHdf5Image.html", "classcarta_1_1CartaHdf5Image" ],
      [ "CartaMiriadImage", "classcarta_1_1CartaMiriadImage.html", "classcarta_1_1CartaMiriadImage" ],
      [ "CasaLoader", "classcarta_1_1CasaLoader.html", "classcarta_1_1CasaLoader" ],
      [ "CompListLoader", "classcarta_1_1CompListLoader.html", "classcarta_1_1CompListLoader" ],
      [ "BeamInfo", "structcarta_1_1BeamInfo.html", "structcarta_1_1BeamInfo" ],
      [ "BeamTableInfo", "structcarta_1_1BeamTableInfo.html", "structcarta_1_1BeamTableInfo" ],
      [ "CompressedFits", "classcarta_1_1CompressedFits.html", "classcarta_1_1CompressedFits" ],
      [ "ConcatLoader", "classcarta_1_1ConcatLoader.html", "classcarta_1_1ConcatLoader" ],
      [ "ExprLoader", "classcarta_1_1ExprLoader.html", "classcarta_1_1ExprLoader" ],
      [ "StokesSlicer", "structcarta_1_1StokesSlicer.html", "structcarta_1_1StokesSlicer" ],
      [ "StokesRegion", "structcarta_1_1StokesRegion.html", "structcarta_1_1StokesRegion" ],
      [ "FileLoader", "classcarta_1_1FileLoader.html", "classcarta_1_1FileLoader" ],
      [ "FitsLoader", "classcarta_1_1FitsLoader.html", "classcarta_1_1FitsLoader" ],
      [ "Hdf5Attributes", "classcarta_1_1Hdf5Attributes.html", "classcarta_1_1Hdf5Attributes" ],
      [ "Hdf5Loader", "classcarta_1_1Hdf5Loader.html", "classcarta_1_1Hdf5Loader" ],
      [ "ImagePtrLoader", "classcarta_1_1ImagePtrLoader.html", "classcarta_1_1ImagePtrLoader" ],
      [ "MiriadLoader", "classcarta_1_1MiriadLoader.html", "classcarta_1_1MiriadLoader" ],
      [ "PolarizationCalculator", "classcarta_1_1PolarizationCalculator.html", "classcarta_1_1PolarizationCalculator" ],
      [ "StokesFilesConnector", "classcarta_1_1StokesFilesConnector.html", "classcarta_1_1StokesFilesConnector" ],
      [ "FitData", "structcarta_1_1FitData.html", "structcarta_1_1FitData" ],
      [ "FitStatus", "structcarta_1_1FitStatus.html", "structcarta_1_1FitStatus" ],
      [ "ImageFitter", "classcarta_1_1ImageFitter.html", "classcarta_1_1ImageFitter" ],
      [ "Image2DConvolver", "classcarta_1_1Image2DConvolver.html", "classcarta_1_1Image2DConvolver" ],
      [ "GeneratedImage", "structcarta_1_1GeneratedImage.html", "structcarta_1_1GeneratedImage" ],
      [ "ImageMoments", "classcarta_1_1ImageMoments.html", "classcarta_1_1ImageMoments" ],
      [ "MomentGenerator", "classcarta_1_1MomentGenerator.html", "classcarta_1_1MomentGenerator" ],
      [ "PvGenerator", "classcarta_1_1PvGenerator.html", "classcarta_1_1PvGenerator" ],
      [ "PreviewCubeParameters", "structcarta_1_1PreviewCubeParameters.html", "structcarta_1_1PreviewCubeParameters" ],
      [ "PvPreviewCube", "classcarta_1_1PvPreviewCube.html", "classcarta_1_1PvPreviewCube" ],
      [ "PreviewCutParameters", "structcarta_1_1PreviewCutParameters.html", "structcarta_1_1PreviewCutParameters" ],
      [ "PvPreviewCut", "classcarta_1_1PvPreviewCut.html", "classcarta_1_1PvPreviewCut" ],
      [ "Bounds", "structcarta_1_1Bounds.html", "structcarta_1_1Bounds" ],
      [ "BasicStats", "structcarta_1_1BasicStats.html", "structcarta_1_1BasicStats" ],
      [ "BasicStatsCalculator", "classcarta_1_1BasicStatsCalculator.html", "classcarta_1_1BasicStatsCalculator" ],
      [ "Histogram", "classcarta_1_1Histogram.html", "classcarta_1_1Histogram" ],
      [ "CartaLogSink", "classcarta_1_1CartaLogSink.html", "classcarta_1_1CartaLogSink" ],
      [ "ProgramSettings", "structcarta_1_1ProgramSettings.html", "structcarta_1_1ProgramSettings" ],
      [ "WebBrowser", "classcarta_1_1WebBrowser.html", "classcarta_1_1WebBrowser" ],
      [ "CrtfImportExport", "classcarta_1_1CrtfImportExport.html", "classcarta_1_1CrtfImportExport" ],
      [ "Ds9ImportExport", "classcarta_1_1Ds9ImportExport.html", "classcarta_1_1Ds9ImportExport" ],
      [ "LineBoxRegions", "classcarta_1_1LineBoxRegions.html", "classcarta_1_1LineBoxRegions" ],
      [ "RegionState", "structcarta_1_1RegionState.html", "structcarta_1_1RegionState" ],
      [ "Region", "classcarta_1_1Region.html", "classcarta_1_1Region" ],
      [ "RegionProperties", "structcarta_1_1RegionProperties.html", "structcarta_1_1RegionProperties" ],
      [ "RegionHandler", "classcarta_1_1RegionHandler.html", "classcarta_1_1RegionHandler" ],
      [ "RegionImportExport", "classcarta_1_1RegionImportExport.html", "classcarta_1_1RegionImportExport" ],
      [ "AnimationObject", "classcarta_1_1AnimationObject.html", "classcarta_1_1AnimationObject" ],
      [ "CursorSettings", "classcarta_1_1CursorSettings.html", "classcarta_1_1CursorSettings" ],
      [ "OnMessageTask", "classcarta_1_1OnMessageTask.html", "classcarta_1_1OnMessageTask" ],
      [ "SetImageChannelsTask", "classcarta_1_1SetImageChannelsTask.html", "classcarta_1_1SetImageChannelsTask" ],
      [ "SetCursorTask", "classcarta_1_1SetCursorTask.html", "classcarta_1_1SetCursorTask" ],
      [ "AnimationTask", "classcarta_1_1AnimationTask.html", "classcarta_1_1AnimationTask" ],
      [ "StartAnimationTask", "classcarta_1_1StartAnimationTask.html", "classcarta_1_1StartAnimationTask" ],
      [ "RegionDataStreamsTask", "classcarta_1_1RegionDataStreamsTask.html", "classcarta_1_1RegionDataStreamsTask" ],
      [ "SpectralProfileTask", "classcarta_1_1SpectralProfileTask.html", "classcarta_1_1SpectralProfileTask" ],
      [ "PvPreviewUpdateTask", "classcarta_1_1PvPreviewUpdateTask.html", "classcarta_1_1PvPreviewUpdateTask" ],
      [ "PerSocketData", "structcarta_1_1PerSocketData.html", "structcarta_1_1PerSocketData" ],
      [ "LoaderCache", "classcarta_1_1LoaderCache.html", "classcarta_1_1LoaderCache" ],
      [ "Session", "classcarta_1_1Session.html", "classcarta_1_1Session" ],
      [ "SessionContext", "classcarta_1_1SessionContext.html", "classcarta_1_1SessionContext" ],
      [ "SessionManager", "classcarta_1_1SessionManager.html", "classcarta_1_1SessionManager" ],
      [ "DataColumn", "classcarta_1_1DataColumn.html", "classcarta_1_1DataColumn" ],
      [ "Column", "classcarta_1_1Column.html", "classcarta_1_1Column" ],
      [ "TableParam", "structcarta_1_1TableParam.html", "structcarta_1_1TableParam" ],
      [ "Table", "classcarta_1_1Table.html", "classcarta_1_1Table" ],
      [ "TableViewCache", "structcarta_1_1TableViewCache.html", "structcarta_1_1TableViewCache" ],
      [ "TableController", "classcarta_1_1TableController.html", "classcarta_1_1TableController" ],
      [ "TableView", "classcarta_1_1TableView.html", "classcarta_1_1TableView" ],
      [ "concurrent_queue", "classcarta_1_1concurrent__queue.html", "classcarta_1_1concurrent__queue" ],
      [ "queuing_rw_mutex", "classcarta_1_1queuing__rw__mutex.html", "classcarta_1_1queuing__rw__mutex" ],
      [ "queuing_rw_mutex_scoped", "classcarta_1_1queuing__rw__mutex__scoped.html", "classcarta_1_1queuing__rw__mutex__scoped" ],
      [ "ThreadManager", "classcarta_1_1ThreadManager.html", "classcarta_1_1ThreadManager" ],
      [ "ListProgressReporter", "classcarta_1_1ListProgressReporter.html", "classcarta_1_1ListProgressReporter" ],
      [ "TimeDelta", "structcarta_1_1TimeDelta.html", "structcarta_1_1TimeDelta" ],
      [ "Timer", "classcarta_1_1Timer.html", "classcarta_1_1Timer" ],
      [ "EventHeader", "structcarta_1_1EventHeader.html", "structcarta_1_1EventHeader" ]
    ] ],
    [ "spdlog", "namespacespdlog.html", [
      [ "sinks", "namespacespdlog_1_1sinks.html", [
        [ "carta_sink", "classspdlog_1_1sinks_1_1carta__sink.html", "classspdlog_1_1sinks_1_1carta__sink" ]
      ] ]
    ] ],
    [ "std", null, [
      [ "hash< carta::TileCacheKey >", "structstd_1_1hash_3_01carta_1_1TileCacheKey_01_4.html", "structstd_1_1hash_3_01carta_1_1TileCacheKey_01_4" ]
    ] ],
    [ "ansicolor_sink", "classansicolor__sink.html", null ],
    [ "AxisRange", "structAxisRange.html", "structAxisRange" ],
    [ "Message", "classMessage.html", "classMessage" ],
    [ "PointXy", "structPointXy.html", "structPointXy" ],
    [ "StokesSource", "structStokesSource.html", "structStokesSource" ]
];