var hierarchy =
[
    [ "carta::AnimationObject", "classcarta_1_1AnimationObject.html", null ],
    [ "ansicolor_sink", "classansicolor__sink.html", [
      [ "spdlog::sinks::carta_sink", "classspdlog_1_1sinks_1_1carta__sink.html", null ]
    ] ],
    [ "AxisRange", "structAxisRange.html", null ],
    [ "carta::BasicStats< T >", "structcarta_1_1BasicStats.html", null ],
    [ "carta::BasicStats< float >", "structcarta_1_1BasicStats.html", null ],
    [ "carta::BasicStatsCalculator< T >", "classcarta_1_1BasicStatsCalculator.html", null ],
    [ "carta::BeamInfo", "structcarta_1_1BeamInfo.html", null ],
    [ "carta::BeamTableInfo", "structcarta_1_1BeamTableInfo.html", null ],
    [ "carta::Bounds< T >", "structcarta_1_1Bounds.html", null ],
    [ "carta::Bounds< double >", "structcarta_1_1Bounds.html", null ],
    [ "carta::CacheId", "structcarta_1_1CacheId.html", null ],
    [ "carta::CacheIdHash", "structcarta_1_1CacheIdHash.html", null ],
    [ "carta::VectorField::CalcFpi", "structcarta_1_1VectorField_1_1CalcFpi.html", null ],
    [ "carta::VectorField::CalcPa", "structcarta_1_1VectorField_1_1CalcPa.html", null ],
    [ "carta::VectorField::CalcPi", "structcarta_1_1VectorField_1_1CalcPi.html", null ],
    [ "carta::Column", "classcarta_1_1Column.html", [
      [ "carta::DataColumn< T >", "classcarta_1_1DataColumn.html", null ]
    ] ],
    [ "carta::BeamTableInfo::ColumnInfo", "structcarta_1_1BeamTableInfo_1_1ColumnInfo.html", null ],
    [ "carta::CompressedFits", "classcarta_1_1CompressedFits.html", null ],
    [ "carta::concurrent_queue< T >", "classcarta_1_1concurrent__queue.html", null ],
    [ "carta::concurrent_queue< std::pair< CARTA::SetImageChannels, uint32_t > >", "classcarta_1_1concurrent__queue.html", null ],
    [ "carta::concurrent_queue< std::pair< std::vector< char >, bool > >", "classcarta_1_1concurrent__queue.html", null ],
    [ "carta::ConfigId", "structcarta_1_1ConfigId.html", null ],
    [ "carta::ConfigIdHash", "structcarta_1_1ConfigIdHash.html", null ],
    [ "carta::ContourSettings", "structcarta_1_1ContourSettings.html", null ],
    [ "carta::CursorSettings", "classcarta_1_1CursorSettings.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "carta::TilePool", "structcarta_1_1TilePool.html", null ]
    ] ],
    [ "carta::EventHeader", "structcarta_1_1EventHeader.html", null ],
    [ "carta::FileExtInfoLoader", "classcarta_1_1FileExtInfoLoader.html", null ],
    [ "carta::FileInfoLoader", "classcarta_1_1FileInfoLoader.html", null ],
    [ "carta::FileListHandler", "classcarta_1_1FileListHandler.html", null ],
    [ "carta::FileLoader", "classcarta_1_1FileLoader.html", [
      [ "carta::CasaLoader", "classcarta_1_1CasaLoader.html", null ],
      [ "carta::CompListLoader", "classcarta_1_1CompListLoader.html", null ],
      [ "carta::ConcatLoader", "classcarta_1_1ConcatLoader.html", null ],
      [ "carta::ExprLoader", "classcarta_1_1ExprLoader.html", null ],
      [ "carta::FitsLoader", "classcarta_1_1FitsLoader.html", null ],
      [ "carta::Hdf5Loader", "classcarta_1_1Hdf5Loader.html", null ],
      [ "carta::ImagePtrLoader", "classcarta_1_1ImagePtrLoader.html", null ],
      [ "carta::MiriadLoader", "classcarta_1_1MiriadLoader.html", null ]
    ] ],
    [ "carta::FitData", "structcarta_1_1FitData.html", null ],
    [ "carta::FitsHduList", "classcarta_1_1FitsHduList.html", null ],
    [ "carta::FitStatus", "structcarta_1_1FitStatus.html", null ],
    [ "carta::Frame", "classcarta_1_1Frame.html", null ],
    [ "carta::GeneratedImage", "structcarta_1_1GeneratedImage.html", null ],
    [ "std::hash< carta::TileCacheKey >", "structstd_1_1hash_3_01carta_1_1TileCacheKey_01_4.html", null ],
    [ "carta::Hdf5Attributes", "classcarta_1_1Hdf5Attributes.html", null ],
    [ "carta::Histogram", "classcarta_1_1Histogram.html", null ],
    [ "carta::HistogramCache", "structcarta_1_1HistogramCache.html", null ],
    [ "carta::HistogramConfig", "structcarta_1_1HistogramConfig.html", null ],
    [ "carta::HttpServer", "classcarta_1_1HttpServer.html", null ],
    [ "carta::ImageFitter", "classcarta_1_1ImageFitter.html", null ],
    [ "casacore::ImageInterface", null, [
      [ "carta::CartaFitsImage", "classcarta_1_1CartaFitsImage.html", null ],
      [ "carta::CartaHdf5Image", "classcarta_1_1CartaHdf5Image.html", null ]
    ] ],
    [ "casa::ImageMomentsProgressMonitor", null, [
      [ "carta::MomentGenerator", "classcarta_1_1MomentGenerator.html", null ]
    ] ],
    [ "carta::FileInfo::ImageStats", "structcarta_1_1FileInfo_1_1ImageStats.html", null ],
    [ "casa::ImageTask", null, [
      [ "carta::Image2DConvolver< T >", "classcarta_1_1Image2DConvolver.html", null ]
    ] ],
    [ "carta::ListProgressReporter", "classcarta_1_1ListProgressReporter.html", null ],
    [ "carta::LoaderCache", "classcarta_1_1LoaderCache.html", null ],
    [ "Message", "classMessage.html", null ],
    [ "casacore::MIRIADImage", null, [
      [ "carta::CartaMiriadImage", "classcarta_1_1CartaMiriadImage.html", null ]
    ] ],
    [ "casa::MomentsBase", null, [
      [ "carta::ImageMoments< casacore::Float >", "classcarta_1_1ImageMoments.html", null ],
      [ "carta::ImageMoments< T >", "classcarta_1_1ImageMoments.html", null ]
    ] ],
    [ "carta::OnMessageTask", "classcarta_1_1OnMessageTask.html", [
      [ "carta::AnimationTask", "classcarta_1_1AnimationTask.html", null ],
      [ "carta::RegionDataStreamsTask", "classcarta_1_1RegionDataStreamsTask.html", null ],
      [ "carta::SetCursorTask", "classcarta_1_1SetCursorTask.html", null ],
      [ "carta::SetImageChannelsTask", "classcarta_1_1SetImageChannelsTask.html", null ],
      [ "carta::SpectralProfileTask", "classcarta_1_1SpectralProfileTask.html", null ],
      [ "carta::StartAnimationTask", "classcarta_1_1StartAnimationTask.html", null ]
    ] ],
    [ "carta::PerSocketData", "structcarta_1_1PerSocketData.html", null ],
    [ "PointXy", "structPointXy.html", null ],
    [ "carta::PolarizationCalculator", "classcarta_1_1PolarizationCalculator.html", null ],
    [ "carta::ProgramSettings", "structcarta_1_1ProgramSettings.html", null ],
    [ "carta::PvGenerator", "classcarta_1_1PvGenerator.html", null ],
    [ "carta::queuing_rw_mutex", "classcarta_1_1queuing__rw__mutex.html", null ],
    [ "carta::queuing_rw_mutex_scoped", "classcarta_1_1queuing__rw__mutex__scoped.html", null ],
    [ "carta::Region", "classcarta_1_1Region.html", null ],
    [ "carta::RegionHandler", "classcarta_1_1RegionHandler.html", null ],
    [ "carta::RegionHistogramConfig", "structcarta_1_1RegionHistogramConfig.html", null ],
    [ "carta::RegionImportExport", "classcarta_1_1RegionImportExport.html", [
      [ "carta::CrtfImportExport", "classcarta_1_1CrtfImportExport.html", null ],
      [ "carta::Ds9ImportExport", "classcarta_1_1Ds9ImportExport.html", null ]
    ] ],
    [ "carta::RegionProperties", "structcarta_1_1RegionProperties.html", null ],
    [ "carta::RegionSpectralConfig", "structcarta_1_1RegionSpectralConfig.html", null ],
    [ "carta::FileInfo::RegionSpectralStats", "structcarta_1_1FileInfo_1_1RegionSpectralStats.html", null ],
    [ "carta::RegionState", "structcarta_1_1RegionState.html", null ],
    [ "carta::RegionStatsConfig", "structcarta_1_1RegionStatsConfig.html", null ],
    [ "carta::FileInfo::RegionStatsId", "structcarta_1_1FileInfo_1_1RegionStatsId.html", null ],
    [ "carta::FileListHandler::ResultMsg", "structcarta_1_1FileListHandler_1_1ResultMsg.html", null ],
    [ "carta::Session", "classcarta_1_1Session.html", null ],
    [ "carta::SessionContext", "classcarta_1_1SessionContext.html", null ],
    [ "carta::SessionManager", "classcarta_1_1SessionManager.html", null ],
    [ "carta::SpectralCache", "structcarta_1_1SpectralCache.html", null ],
    [ "carta::SpectralConfig", "structcarta_1_1SpectralConfig.html", null ],
    [ "carta::StatsCache", "structcarta_1_1StatsCache.html", null ],
    [ "carta::StokesFilesConnector", "classcarta_1_1StokesFilesConnector.html", null ],
    [ "carta::StokesRegion", "structcarta_1_1StokesRegion.html", null ],
    [ "carta::StokesSlicer", "structcarta_1_1StokesSlicer.html", null ],
    [ "StokesSource", "structStokesSource.html", null ],
    [ "carta::Table", "classcarta_1_1Table.html", null ],
    [ "carta::TableController", "classcarta_1_1TableController.html", null ],
    [ "carta::TableParam", "structcarta_1_1TableParam.html", null ],
    [ "carta::TableView", "classcarta_1_1TableView.html", null ],
    [ "carta::TableViewCache", "structcarta_1_1TableViewCache.html", null ],
    [ "carta::ThreadManager", "classcarta_1_1ThreadManager.html", null ],
    [ "carta::VectorField::ThresholdCut", "structcarta_1_1VectorField_1_1ThresholdCut.html", null ],
    [ "carta::Tile", "structcarta_1_1Tile.html", null ],
    [ "carta::TileCache", "classcarta_1_1TileCache.html", null ],
    [ "carta::TileCacheKey", "structcarta_1_1TileCacheKey.html", null ],
    [ "carta::TilePool::TilePtrDeleter", "structcarta_1_1TilePool_1_1TilePtrDeleter.html", null ],
    [ "carta::TimeDelta", "structcarta_1_1TimeDelta.html", null ],
    [ "carta::Timer", "classcarta_1_1Timer.html", null ],
    [ "carta::VectorField::Valid", "structcarta_1_1VectorField_1_1Valid.html", null ],
    [ "carta::VectorField", "classcarta_1_1VectorField.html", null ],
    [ "carta::WebBrowser", "classcarta_1_1WebBrowser.html", null ]
];