FROM ubuntu:20.04

# Install the basic packages
RUN \
  apt-get update && \
  apt-get -y upgrade && \
  DEBIAN_FRONTEND=noninteractive \
  apt-get install -y apt-utils autoconf bison build-essential cmake curl fftw3-dev flex gcc g++ \
    gdb gfortran git git-lfs libgmock-dev googletest libblas-dev libcfitsio-dev \
    libgsl-dev libgtest-dev libhdf5-dev liblapack-dev libncurses-dev \
    libprotobuf-dev libreadline-dev libssl-dev libstarlink-ast-dev \
    libtool libxml2-dev libxslt1-dev libzstd-dev pkg-config protobuf-compiler \
    python3-numpy python3-astropy software-properties-common unzip wcslib-dev wget uuid-dev

# Get carta dependencies carta-casacore, fits2idia, and zfp from cartavis-team PPA and casacore-data from KERN
RUN \
  apt-add-repository -y -s ppa:kernsuite/kern-7 && \
  add-apt-repository -y ppa:cartavis-team/carta && \
  apt-get update && \
  apt-get -y install carta-casacore-dev fits2idia libzfp-dev

# Forward port so that the webapp can properly access it from outside of the container
EXPOSE 3002

ENV HOME /root
WORKDIR /root

# Overwrite this with 'CMD []' in a dependent Dockerfile
CMD ["bash"]

