FROM ubuntu:18.04

# Update and pull down build tools
RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y apt-utils autoconf bison build-essential byobu curl default-jre dialog emacs \
    fftw3-dev flex gdb g++-8 gcc-8 gfortran git git-lfs htop libblas-dev libcurl4-gnutls-dev \
    libpugixml-dev libcfitsio-dev libgtest-dev libhdf5-dev liblapack-dev libncurses-dev \
    libreadline-dev libssl-dev libstarlink-ast-dev libtbb-dev libtool \
    libxml2-dev libzstd-dev libgsl-dev man pkg-config python-pip python3-pip \
    software-properties-common unzip vim wcslib-dev wget uuid-dev && \
  update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8

# carta_backend unit tests require cmake >3.12 but ubuntu 18.04 provides 3.10.2
RUN \
  cd /root && \
  git clone https://github.com/Kitware/CMake.git && \
  cd CMake && git checkout v3.20.0 && ./configure && \
  make -j 2 && make install && \
  cd /root && rm -rf CMake

# Get carta dependencies from the cartavis-team PPA (includes casacore-data)
RUN \
  ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone && \
  add-apt-repository -y ppa:cartavis-team/carta && \
  apt-get -y update && \
  apt-get -y install casacore-dev googletest libgrpc++-dev libprotobuf-dev libzfp-dev protobuf-compiler-grpc 

# Forward port so that the webapp can properly access it
# from outside of the container
EXPOSE 3002
# Do the same with the gRPC service port
EXPOSE 50051

ENV HOME /root
# Required for running the backend
ENV LD_LIBRARY_PATH /usr/local/lib
ENV CASAPATH "/usr/share/casacore linux local `hostname`"

WORKDIR /root

# overwrite this with 'CMD []' in a dependent Dockerfile
CMD ["bash"]

