FROM ubuntu:20.04

# Install the basic packages
RUN \
  apt-get update && \
  apt-get -y upgrade && \
  DEBIAN_FRONTEND=noninteractive \
  apt-get install -y apt-utils autoconf bison build-essential cmake curl fftw3-dev flex gcc g++ \
    gdb gfortran git git-lfs googletest libblas-dev libcfitsio-dev libcurl4-gnutls-dev libfmt-dev \
    libgrpc-dev libgrpc++-dev libgsl-dev libgtest-dev libhdf5-dev liblapack-dev libncurses-dev \
    libprotobuf-dev libpugixml-dev libreadline-dev libssl-dev libstarlink-ast-dev libtool libtbb-dev \
    libxml2-dev libxslt1-dev libzstd-dev pkg-config protobuf-compiler-grpc software-properties-common \
    unzip wcslib-dev wget

# Get carta dependencies
# casacore data from Kernsuite PPA
RUN \
  apt-add-repository -y -s ppa:kernsuite/kern-7 && \
  apt-get update && \
  apt-get -y install casacore-data

# carta-casacore from cartavis PPA
RUN \
  add-apt-repository -y ppa:cartavis/carta-casacore && \
  apt-get update && \
  apt-get install carta-casacore

# uWS from cartavis PPA
RUN \
  add-apt-repository -y ppa:cartavis/uws && \
  apt-get update && \
  apt-get install uws

# zfp from cartavis PPA
RUN \
  add-apt-repository -y ppa:cartavis/zfp && \
  apt-get update && \
  apt-get install zfp

# Forward port so that the webapp can properly access it from outside of the container
EXPOSE 3002
# Do the same with the gRPC service port
EXPOSE 50051

ENV HOME /root

# Required for running the backend 
ENV LD_LIBRARY_PATH "/usr/lib64:/usr/local/lib:$LD_LIBRARY_PATH"
ENV CASAPATH "/usr/share/casacore linux local `hostname`"

WORKDIR /root

# Overwrite this with 'CMD []' in a dependent Dockerfile
CMD ["bash"]

