FROM centos:7

# The carta-backend will use GCC 8 functions, so install and activate devtoolset-8 
RUN \
  yum -y install centos-release-scl && \
  yum install -y centos-release-scl && yum install -y devtoolset-8-gcc devtoolset-8-gcc-c++ devtoolset-8-gcc-gfortran && \
  echo "source scl_source enable devtoolset-8" >> /etc/bashrc

# Install the required packages
RUN \
  yum -y install centos-release-openstack-train && \
  yum -y install epel-release && \
  yum install -y autoconf automake bison blas-devel bzip2 cfitsio-devel cmake3 curl-devel flex \
    git git-lfs gsl-devel grpc-devel grpc-plugins gtest-devel hdf5-devel lapack-devel libtool libxml2-devel libzstd-devel \
    make openssl-devel protobuf-devel pugixml-devel readline-devel subversion systemd-devel wcslib-devel wget \
    zlib-devel libuuid-devel zfp-devel && \
  ln -s /usr/bin/cmake3 /usr/bin/cmake

# CARTA will have a problem finding the .h files in /usr/include/cfitsio/
RUN \
  source /etc/bashrc && \
  cp /usr/include/cfitsio/* /usr/include/

# Get geodetic and ephemerides casa-data
RUN \
  source /etc/bashrc && \
  mkdir -p /usr/local/share/casacore/data/ephemerides && \
  mkdir -p /usr/local/share/casacore/data/geodetic && \
  svn co https://svn.cv.nrao.edu/svn/casa-data/distro/ephemerides/ /usr/local/share/casacore/data/ephemerides && \
  svn co https://svn.cv.nrao.edu/svn/casa-data/distro/geodetic/ /usr/local/share/casacore/data/geodetic && \
  rm -r /usr/local/share/casacore/data/ephemerides/splatalogue.db && \
  rm -r /usr/local/share/casacore/data/ephemerides/SplatDefault.tbl

# Get libsofa.a for casacore
RUN \
  source /etc/bashrc && \
  wget http://www.iausofa.org/2018_0130_F/sofa_f-20180130.tar.gz && \
  tar xzf sofa_f-20180130.tar.gz && rm sofa_f-20180130.tar.gz && \
  cd sofa/20180130/f77/src && make && cp libsofa.a /usr/lib/libsofa.a && \
  cd /root && rm -rf sofa

# Install carta-casacore from CARTAvis repo (with fixed CASAROOT)
RUN \
  source /etc/bashrc && \
  cd /root && \
  git clone https://github.com/CARTAvis/carta-casacore.git && \
  cd carta-casacore && \
  git submodule init && git submodule update && \
  cd casa6 && \
  git submodule init && git submodule update && \
  cd ../ && mkdir -p build && cd build && \
  cmake .. -DUSE_FFTW3=ON \
           -DUSE_HDF5=ON \
           -DUSE_THREADS=ON \
           -DUSE_OPENMP=ON \
           -DCMAKE_BUILD_TYPE=Release \
           -DBUILD_TESTING=OFF \
           -DBUILD_PYTHON=OFF \
           -DUseCcache=1 \
           -DHAS_CXX11=1 \
           -DDATA_DIR=/usr/local/share/casacore/data \
           -DCMAKE_INSTALL_PREFIX=/opt/carta-casacore && \
  make -j2 && make install && \
  cd /root && rm -rf carta-casacore

# CARTA has a problem with CentOS7 tbb 4.1, so install a newer version:
RUN \
  source /etc/bashrc && \
  cd /root && \
  git clone https://github.com/wjakob/tbb.git && \
  cd tbb/build && cmake .. && make && make install && \
  cd /root && rm -rf tbb

# Forward port so that the webapp can properly access it
# from outside of the container
EXPOSE 3002
# Do the same with the gRPC service port
EXPOSE 50051

ENV LD_LIBRARY_PATH "/usr/local/lib"

ENV HOME /root
WORKDIR /root

# overwrite this with 'CMD []' in a dependent Dockerfile
CMD ["bash"]

