FROM ubuntu:16.04

# Install the basic packages
RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y apt-utils autoconf bison build-essential byobu curl fftw3-dev flex \
    gdb gfortran git htop libblas-dev libcfitsio-dev libcurl4-gnutls-dev libgsl-dev \
    libgtest-dev libhdf5-dev liblapack-dev libncurses-dev libreadline-dev \
    libssl-dev libstarlink-ast-dev libtool libtbb-dev libxml2-dev libxslt1-dev \
    libx11-dev libzstd-dev pkg-config software-properties-common unzip wcslib-dev wget

# grpc from webispy ppa
RUN \
  add-apt-repository ppa:webispy/grpc && \
  apt-get update && \
  apt-get install -y libprotobuf-dev protobuf-compiler libgrpc++-dev libgrpc-dev protobuf-compiler-grpc googletest

# The carta-backend will use GCC 8 functions, so install gcc-8
RUN \
  add-apt-repository ppa:ubuntu-toolchain-r/test && \
  apt-get update && \
  apt-get -y install gcc-8 g++-8 && \
  update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8

# 16.04 comes with cmake 3.5.1 but CARTA needs cmake >3.10
RUN \
  cd /root && \
  git clone https://github.com/Kitware/CMake.git && \
  cd CMake && git checkout v3.17.0 && ./configure && \
  make -j 2 && make install && \
  cd /root && rm -rf CMake

# Ubuntu 16.04 does not have libfmt-dev so build it from source
RUN \
  git clone https://github.com/fmtlib/fmt.git && cd fmt && cmake CMakeLists.txt && \
  make && make install && cd .. && rm -rf fmt

# Install spdlog with external 'fmt' library support
RUN \
  cd /root && \
  git clone https://github.com/gabime/spdlog && \
  mkdir -p spdlog/build && cd spdlog/build && \
  cmake .. -DSPDLOG_FMT_EXTERNAL=ON && \
  make && make install && \
  cd /root && rm -rf spdlog

# Install a newer pugixml from source
RUN \
  cd /root && \
  git clone https://github.com/zeux/pugixml && \
  mkdir -p pugixml/build && cd pugixml/build && \
  CXXFLAGS="-DPUGIXML_COMPACT=1 -DPUGIXML_NO_XPATH=1" cmake -DCMAKE_BUILD_TYPE=RELEASE .. && \
  make && make install && \
  cd /root && rm -rf pugixml

# For the casacore 'data' directory, git-lfs difficult to install on 16.04,
# but can conveniently get the appropriate casacore-data from the KERN PPA
RUN \
  add-apt-repository ppa:kernsuite/kern-5 && \
  apt-get update && apt-get install casacore-data && \
  mv /usr/share/casacore /usr/local/share/

# Install carta-casacore (with fixed CASAROOT)
RUN \
  cd /root && \
  git clone -q --recursive https://open-bitbucket.nrao.edu/scm/casa/carta-casacore.git && \
  mkdir -p carta-casacore/build && cd carta-casacore/build && \
  cmake .. -DUSE_FFTW3=ON \
           -DUSE_HDF5=ON \
           -DUSE_THREADS=ON \
           -DUSE_OPENMP=ON \
           -DCMAKE_BUILD_TYPE=Release \
           -DBUILD_TESTING=OFF \
           -DBoost_NO_BOOST_CMAKE=1 \
           -DBUILD_PYTHON=OFF \
           -DUseCcache=1 \
           -DHAS_CXX11=1 \ 
           -DDATA_DIR=/usr/local/share/casacore/data && \
  make && make install && \
  cd /root && rm -rf carta-casacore

# Install zfp
RUN \
  cd /root && \
  git clone https://github.com/LLNL/zfp.git && \
  mkdir -p zfp/build && cd zfp/build && \
  cmake  -DCMAKE_BUILD_TYPE=RELEASE .. && make all install && \
  cd /root && rm -rf zfp

# Install uWS
RUN \
  cd /root && \
  git clone https://github.com/uNetworking/uWebSockets.git && \
  cd uWebSockets && git checkout v0.14 && cd .. && \
  make default install -C uWebSockets && \
  rm -rf uWebSockets

# Forward port so that the webapp can properly access it from outside of the container
EXPOSE 3002
# For gRPC scripting interface
EXPOSE 50051

ENV HOME /root
# Required for running the backend 
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
ENV CASAPATH "/usr/local/share/casacore linux local `hostname`"

WORKDIR /root

# Overwrite this with 'CMD []' in a dependent Dockerfile
CMD ["bash"]

