FROM centos:8.4.2105

# Install the required packages
RUN \
  dnf -y install epel-release && \
  dnf -y install 'dnf-command(config-manager)' && \
  dnf -y config-manager --set-enabled powertools && \
  dnf -y install centos-release-openstack-victoria && \
  dnf -y update && \
  dnf -y install autoconf automake bison blas-devel bzip2 cfitsio-devel cmake curl-devel flex gcc \
         gcc-c++ grpc-devel grpc-plugins git git-lfs gsl-devel hdf5-devel lapack-devel \ 
         libtool libxml2-devel libzstd-devel libuuid-devel make openssl-devel protobuf-devel \
         python36 python3-pip pugixml-devel readline-devel subversion tbb-devel \
         wcslib-devel wget zlib-devel libuuid-devel zfp-devel && \
  pip3 install numpy astropy

# CARTA will have a problem finding the .h files in /usr/include/cfitsio/
RUN \
  source /etc/bashrc && \
  cp /usr/include/cfitsio/* /usr/include/

# Get carta dependencies from the cartavis rpm repository
RUN \
  curl https://packages.cartavis.org/cartavis-el8.repo --output /etc/yum.repos.d/cartavis.repo && \
  yum -y install carta-casacore-devel gtest-devel gmock-devel fits2idia measures-data

# Forward port so that the webapp can properly access it
# from outside of the container
EXPOSE 3002
# Do the same with the gRPC service port
EXPOSE 50051

ENV HOME /root
WORKDIR /root

# overwrite this with 'CMD []' in a dependent Dockerfile
CMD ["bash"]
