FROM centos:7

# The carta-backend will use GCC 8 functions, so install and activate devtoolset-8 
RUN \
  yum -y install centos-release-scl && \
  yum install -y centos-release-scl && yum install -y devtoolset-8-gcc devtoolset-8-gcc-c++ devtoolset-8-gcc-gfortran && \
  echo "source scl_source enable devtoolset-8" >> /etc/bashrc

# Install the required packages
RUN \
  yum -y install centos-release-openstack-train && \
  yum -y install epel-release && \
  yum install -y autoconf automake bison blas-devel bzip2 cfitsio-devel cmake3 curl-devel flex \
    git git-lfs gsl-devel hdf5-devel lapack-devel libtool libxml2-devel libzstd-devel \
    make openssl-devel protobuf-devel pugixml-devel python3 readline-devel subversion systemd-devel wcslib-devel wget \
    zlib-devel libuuid-devel zfp-devel && \
  pip3 install numpy astropy && \
  ln -s /usr/bin/cmake3 /usr/bin/cmake

# Get carta dependencies from the cartavis rpm repository
RUN \ 
  curl https://packages.cartavis.org/cartavis-el7.repo --output /etc/yum.repos.d/cartavis.repo && \
  yum -y install carta-casacore-devel gtest-devel gmock-devel fits2idia measures-data

# Forward port so that the webapp can properly access it
# from outside of the container
EXPOSE 3002

ENV LD_LIBRARY_PATH "/usr/local/lib"
ENV PKG_CONFIG_PATH "/usr/local/lib/pkgconfig"

ENV HOME /root
WORKDIR /root

# overwrite this with 'CMD []' in a dependent Dockerfile
CMD ["bash"]

