#!/usr/bin/env python3
import sys
import subprocess

if __name__ == "__main__":
    args = ["carta_backend"]
    
    if "-host" not in sys.argv and "--host" not in sys.argv:
        result = subprocess.run(["hostname", "-I"], capture_output=True)
        if not result.returncode:
            hostname = result.stdout.split()[0]
            args.extend(["-host", hostname]) # Update this when argument format changes 
        else:
            print(f"Could not set default host IP: {result.stderr}", file = sys.stderr)
    
    args.extend(sys.argv[1:])
    
    # Special sauce undocumented help flag has to come first
    for helpflag in "-h", "--help":
        if helpflag in args:
            args.remove(helpflag)
            args.insert(1, helpflag)
    
    subprocess.run(args)
