#!/bin/bash

UPDATE_INTERVAL=7
AUTOUPDATE_ENABLED="false"
DIR="$HOME/.carta/data"


function check_json_settings {
    # False JSON parsing
    # Remove spaces, comma, and quotes, then replace colon with one space to get two columns of key-value pairs
    # Finally filter the key-value pair using awk and print the value (2nd column)
    JSON_AUTO_UPDATE_CASA=$(cat ~/.carta/backend.json | sed -e 's/[",{}]//g;s/[[:space:]]//g;s/:/ /g' | awk -F" " '$1=="auto_update_casa_data" {print $2}')
    if [ "$JSON_AUTO_UPDATE_CASA" == "true" ]
    then
        AUTOUPDATE_ENABLED="true"
    fi
    JSON_AUTO_UPDATE_CASA_DATA_INTERVAL=$(cat ~/.carta/backend.json | sed -e 's/[",{}]//g;s/[[:space:]]//g;s/:/ /g' | awk -F" " '$1=="auto_update_casa_data_interval" {print $2}')
    if [ $JSON_AUTO_UPDATE_CASA_DATA_INTERVAL -gt 0 ]
    then
        UPDATE_INTERVAL=$JSON_AUTO_UPDATE_CASA_DATA_INTERVAL
    fi
}

function check_cmd_status {
    STATUS=$?
    if [ $STATUS -ne 0 ]
    then
        echo "Something went wrong. Exiting."
        exit $STATUS
    fi
}

function autoupdate {
    SVN="svn"
    SVN_CMD="export --quiet --force"

    if ! [ -x "$(command -v $SVN)" ]
    then
        echo "ERROR: $SVN command not found" >&2
        exit 1
    fi

    $SVN $SVN_CMD https://svn.cv.nrao.edu/svn/casa-data/distro/ephemerides/ $DIR/ephemerides
    check_cmd_status # check if status code is zero and exit if not

    $SVN $SVN_CMD https://svn.cv.nrao.edu/svn/casa-data/distro/geodetic/ $DIR/geodetic
    check_cmd_status # check if status code is zero and exit if not

    rm -r $DIR/ephemerides/splatalogue.db
    check_cmd_status # check if status code is zero and exit if not

    rm -r $DIR/ephemerides/SplatDefault.tbl
    check_cmd_status # check if status code is zero and exit if not

    echo "$(date +%Y-%m-%d)" > $DIR/last_update
    sleep 0.6 # let the progress bar update end
}

function datediff {
    # this part needs improvement, it fails for changing years
    # better: https://stackoverflow.com/questions/4946785/how-to-find-the-difference-in-days-between-two-dates
    PREV=$(cat $DIR/last_update)
    TODAY=$(date +%Y-%m-%d)
    DIFF=$((PREV-TODAY))
    echo $DIFF
}

function launch_auto_update {
    # http://mywiki.wooledge.org/BashFAQ/034
    autoupdate &
    local i=0
    local sp='/-\|'
    local n=${#sp}
    printf ' '
    sleep 0.1
    while ! [ -f $DIR/last_update ]; do
        printf '\b%s' "${sp:i++%n:1}"
        sleep 0.2
    done
    # done
    printf '\b%s' ''
    printf "Update completed successfully on $(date).\n"
}

function autoupdate_if_needed {
    if [ $AUTOUPDATE_ENABLED == "true" ]
    then
        if [ ! -d $DIR ]
        then
            mkdir -p $DIR # will make a directory if it doesn't exist
        fi
        if [ -f $DIR/last_update ]
        then
            DATE_DIFF=$(datediff)
            if [ $DATE_DIFF -gt $UPDATE_INTERVAL ]
            then
                echo "CASA data has not been updated in $DATE_DIFF days. CARTA will try to update the ephemerides and geodetic data now."
                rm $DIR/last_update
                launch_auto_update
            else
                echo "CASA data has been updated in the last $DATE_DIFF days. CARTA will not update the ephemerides and geodetic data."
                exit 0
            fi
        else
            echo "CASA data has not been updated. CARTA will attempt to update automatically."
            launch_auto_update
        fi
    else
        echo "CARTA will use the default ephemerides and geodetic data."
        exit 0
    fi
}


# Logic starts here
# Check JSON for backend.json settings
check_json_settings
echo "AUTOUPDATE ENABLED = $AUTOUPDATE_ENABLED"
echo "UPDATE INTERVAL = $UPDATE_INTERVAL"
# Launch auto update
autoupdate_if_needed
